name: Pre-release

on:
  pull_request:
    branches: [main, experimental, adapters-api]
    paths:
      - packages/open-next/**
  push:
    branches: [main, experimental, adapters-api]
    paths:
      - packages/open-next/**

jobs:
  release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: 22


      - name: Build package
        run: pnpm -F @opennextjs/aws build

      - name: Publish prerelease
        run: pnpm exec pkg-pr-new publish --pnpm --compact './packages/open-next'
