name: Pre-release

on: workflow_dispatch

jobs:
  release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/pnpm-setup

      - name: Install dependencies
        run: pnpm install

      - name: Check codestyle
        run: pnpm lint

      - name: Publish Pre-release to npm
        run: pnpm release-snapshot
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
