name: v2-release

on: workflow_dispatch

jobs:
  release:
    name: Pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: 22

      - name: Publish Pre-release to npm
        run: pnpm release-v2
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
